DROP TABLE IF EXISTS TIENDA;

CREATE TABLE  "TIENDA" (
	"IDTIENDA" NUMBER NOT NULL PRIMARY KEY,
    "NOMBRE" VARCHAR2(100) NOT NULL,
    "CIUDAD" VARCHAR2(100) NOT NULL,
    "DIRECCION" VARCHAR2(100),
    "TELEFONO" VARCHAR2(100),
    "HORARIO" VARCHAR2(100)

);